In [20]:
import pandas as pd

In [21]:
tr_data = pd.read_csv("clean_data/temiz_turkce_data.csv")
en_data = pd.read_csv("clean_data/temiz_ingilizce_data.csv")

In [22]:
tr_data.head()

   label                                         clean_text
0      0                                     iki yıldız iyi
1      0  bir yıldız kargo sorunsuz geldi ama tam haftad...
2      0  kokusu dışında iş görür çok fazla koku yapıyor...
3      0  kötü saat içinden çıkıyor beklediğim kaliteli ...
4      0  çok kötü almayın çok kötü boşa para verirsiniz...

In [23]:
en_data.head()

   label                                         clean_text
0      0  disappointed book just finished moonlight love...
1      0  film cute but lacks cleverness comedy comedies...
2      0  book arrived crumpled front cover not possible...
3      1  like michigans luvd ones toiled largely unnoti...
4      0  sparse usasge couple minutes every months mach...

In [24]:
en_data["label"].value_counts()

label
0    50029
1    49971
Name: count, dtype: int64

In [25]:
tr_positive = tr_data[tr_data["label"] == 1].sample(n=50000, random_state=42)
tr_negative = tr_data[tr_data["label"] == 0].sample(n=50000, random_state=42)

In [26]:
tr_positive

        label                                         clean_text
175721      1  beş yıldız ışıl ışıl tertemiz saçlar güzel tav...
180184      1  ben aldım fiyatı düştü aldıktan sonra fiyat tl...
119864      1  kalite güzel paketlenmiş hediye ayrıca teşekkü...
176699      1  mükemmel saatten erken ulaştı elime çok hızlı ...
192991      1  beş yıldız gerçek anlamda önemli ay kullanılan...
...       ...                                                ...
133072      1    güzel hızlı sıcak şık hızlı gönderi teşekkürler
195599      1               dört yıldız ıphone s çalışıyor güzel
128006      1                           beş yıldız memnun kaldım
190487      1  gayet iyi kurulumu basit eksiksiz geldi ürün k...
158540      1  beş yıldız çok severek kullandığım bir ürün ke...

[50000 rows x 2 columns]

In [27]:
tr_negative

       label                                         clean_text
75721      0  fena değil inandığım olay burda gerçekleşti he...
80184      0  bir yıldız sokaktaki köpeklere verdim yemedile...
19864      0  kalıtelı ama ürün gün içindeulaştı kaliteli ya...
76699      0  duvara çok yakın ürün güzel ancak duvara çok y...
92991      0          bir yıldız ortalama saatte kaynatabiliyor
...      ...                                                ...
33072      0  dolu daha iyi daha önce dolu marka olanını kul...
95599      0  iki yıldız kurmalı filan değil tekerlekli tuha...
28006      0            bir yıldız urun çok geç kargoya verildi
90487      0   kalitesiz kalitesiz malzeme açma kapama tuşu yok
58540      0  aşırı derecede abartılmış tamamen ticari amaçl...

[50000 rows x 2 columns]

In [28]:
tr_final = pd.concat([tr_positive,tr_negative])
tr_final.head()

        label                                         clean_text
175721      1  beş yıldız ışıl ışıl tertemiz saçlar güzel tav...
180184      1  ben aldım fiyatı düştü aldıktan sonra fiyat tl...
119864      1  kalite güzel paketlenmiş hediye ayrıca teşekkü...
176699      1  mükemmel saatten erken ulaştı elime çok hızlı ...
192991      1  beş yıldız gerçek anlamda önemli ay kullanılan...

In [29]:
tr_final = tr_final.sample(frac=1, random_state=42).reset_index(drop=True)

tr_final.head()

   label                                         clean_text
0      0  eh kullanılabilir ev kullanıcıları tavsiye ede...
1      0  uzak durun backlight bleed denilen ekranda gör...
2      1  kullanışlı tam aradığım model hemen sipariş ve...
3      0  aşırı yanma yapıyor bildiğin karanfil yağı kok...
4      0  aparatları yok ürün güzel ama icindeki aparatl...

In [30]:
tr_final["label"].value_counts()

label
0    50000
1    50000
Name: count, dtype: int64

In [31]:
final_data = pd.concat([tr_final, en_data],ignore_index=True)
final_data = final_data.sample(frac=1, random_state=42).reset_index(drop=True)

In [32]:
final_data.head()

   label                                         clean_text
0      0  ordered dark cherries received gooseberries so...
1      0  beğenmedim ürünün kalıbı berbat aldığım ayakka...
2      0  bought sandal wanted more stylish but casual s...
3      0                                    bir yıldız kötü
4      1  kedim bayıldı öncelikle ürün gayet kaliteli ke...

In [33]:
print("Sınıf Dağılımı:\n", final_data['label'].value_counts())
print("\nToplam Veri Sayısı:", len(final_data))

Sınıf Dağılımı:
 label
0    100029
1     99971
Name: count, dtype: int64

Toplam Veri Sayısı: 200000

In [34]:
final_data.rename(columns={'clean_text': 'description'}, inplace=True)

final_data.head()

   label                                        description
0      0  ordered dark cherries received gooseberries so...
1      0  beğenmedim ürünün kalıbı berbat aldığım ayakka...
2      0  bought sandal wanted more stylish but casual s...
3      0                                    bir yıldız kötü
4      1  kedim bayıldı öncelikle ürün gayet kaliteli ke...

In [35]:
nan_rows = final_data[final_data.isnull().any(axis=1)]

print(nan_rows)
print(nan_rows.index)
final_data = final_data.dropna(subset=["description"])

       label description
23668      0         NaN
Index([23668], dtype='int64')

In [36]:
final_data.to_csv("clean_data/temiz_genel_veri.csv", index=False)
print("Birleşik Veri Kaydedildi")

Birleşik Veri Kaydedildi